
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itlpvpdwgiwbdpqheemw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bHB2cGR3Z2l3YmRwcWhlZW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxOTA5NzEsImV4cCI6MjA1NTc2Njk3MX0.gljQ6JAfbMzP-cbA68Iz21vua9YqAqVQgpB-eLk6nAg";

// Define custom function interfaces
type CustomFunctions = {
  get_payment_reminder_settings: {
    Args: Record<string, never>;
    Returns: { 
      id: number;
      notification_time: string;
      days_interval: number;
      active: boolean;
    };
  };
  update_payment_reminder_settings: {
    Args: {
      p_notification_time: string;
      p_days_interval: number;
      p_active: boolean;
    };
    Returns: null;
  };
  check_billing_notifications: Database['public']['Functions']['check_billing_notifications'];
  insert_template_if_not_exists: Database['public']['Functions']['insert_template_if_not_exists'];
  trigger_billing_notifications: Database['public']['Functions']['trigger_billing_notifications'];
  trigger_notifications: Database['public']['Functions']['trigger_notifications'];
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database & { public: { Functions: CustomFunctions } }>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY
);
